command.showStatusBarMenu.name=Show Copilot Status Menu
command.triggerInlineSuggestions.name=Trigger Inline Suggestion
command.acceptFullSuggestion.name=Accept Suggestion
command.acceptNextWord.name=Accept Next Word
command.discardSuggestion.name=Discard Suggestion
command.copilotForEclipsePlugin.name=GitHub Copilot
command.signInToGitHub.name=Sign in to GitHub Copilot
command.showChatView.name=Open Chat
command.signOutFromGitHub.name=Sign Out from GitHub
command.configureCopilotSettings.name=Activate GitHub Copilot Account... 
command.viewFeedbackForum.name=View Feedback Forum
command.openFeedbackForum.name=View Feedback Forum...
command.openPreferencesPage.name=Edit Preferences...
command.openPreferencesPage.parameter.name=Page Name
command.openEditKeyboardShortcuts.name=Edit Keyboard Shortcuts...
command.autoShowCompletions.name=Enable/Disable Auto Show Completions
command.showWhatIsNew.name=Show What's New

page.preferencesPage.name=GitHub Copilot
page.showViewPage.name=GitHub Copilot
page.showViewPageShowChatView.name=Chat