command.triggerInlineSuggestions.name=Trigger Inline Suggestion
command.acceptFullSuggestion.name=Accept Suggestion
command.discardSuggestion.name=Discard Suggestion
command.copilotForEclipsePlugin.name=GitHub Copilot for Eclipse
command.signInToGitHub.name=Sign in to GitHub Copilot
command.signOutFromGitHub.name=Sign out from GitHub Copilot
command.viewFeedbackForum.name=View Feedback Forum