name: Sync microsoft/copilot-eclipse-collaboration

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    checkout-and-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  ref: 'refs/heads/main' # Push from the main branch
                  fetch-depth: '0' # Checkout full history
                  fetch-tags: true

            # The http.extraheader config must be set to https://github.com to
            # override the auth configured by the actions/checkout action
            - name: Configure git to push to microsoft/copilot-eclipse-collaboration
              run: |
                  git config user.email "actions@github.com"
                  git config user.name "Actions Auto Build"
                  header="$(echo -n x-access-token:${{ secrets.GH_COPILOT_ECLIPSE_FORK }} | base64 | tr -d '\n')"
                  git config --local http.https://github.com/.extraheader "Authorization: basic $header"
                  git remote add msft 'https://github.com/microsoft/copilot-eclipse-collaboration.git'

            - name: Push to microsoft/copilot-eclipse-collaboration
              run: git push --tags msft main
